### PR TITLE
Feature/24-Consolidate-filtered-issue-actions

### LINKED ISSUE #24: Consolidate Issue filter actions to one controller action
Currently we have:
- All isses
- Filtered by language
- Filtered by label.

I would suggest to consolidate that to a single issue and make the filter potentiallly combinabile. so urls would look like:

/i/?filter[language]=php&filter[label]=feature etc.
That would drastically reduce the amount of code in controller and view.

### PR DESCRIPTION
**Pull request by pulponair**
Resolves #24 

Just one action for issues:

All issues 
/i

Filtered by language
/i?filter[language]=Python

Filtered by label
i?filter[label]=enhancement

Combined filters:
/i?filter[language]=Python&filter[label]=enhancement

Headlines are adjusted according to filters.
image

### CODE REVIEW

**Comment by erikaheidi** [comment]
Hmm it seems this needs a rebase to current master. Would you be so kind to do it? :) Thank you so much for this contribution, it's a great improvement. :clap:

**Comment by pulponair** [comment]
@erikaheidi done :)

**Comment by pulponair** [comment]
done again;)

**Comment by erikaheidi** [comment]
Thank you! I was just pulling it here to try to merge :P Good job!

**Comment by erikaheidi** [comment]
Deployed :+1:

**Pull request merged**
