### PR TITLE
Fixes #15 - per entity controllers

### LINKED ISSUE #15: Use per Entity Controller
Currently everthing is handled by the MainController. I suggest to have a dedicated Controller per Entity in order to have play along the SoC paradigm.

### PR DESCRIPTION
**Pull request by erikaheidi**
Created per-entity controllers.

### CODE REVIEW

**Comment by erikaheidi** [comment]
Can you have a look at this, since you created the original issue? :) @pulponair

**Comment by pulponair** [comment]
@erikaheidi sure i ll tonight

**Comment by pulponair** [comment]
@erikaheidi 
Ok here we go: 

1. I would use a consisting RestFull naming for controller actions (quoting Rob Conery here ):
--
* Index - the main "landing" page. This is also the default endpoint.
* List - a list of whatever "thing" you're showing them - like a list of Products.
* Show - a particular item of whatever "thing" you're showing them (like a Product)
* Edit - an edit page for the "thing"
* New - a create page for the "thing"
* Create - creates a new "thing" (and saves it if you're using a DB)
* Update - updates the "thing"
* Delete - deletes the "thing"
--

2. Rename the named routes to controllerName.Action

3. We should consider suffixing actions with "Action" e.g. IssueController->listAction. 
This makes it easier to see if a function is a mvc action or a controller helper fuction. 

4. Consider moving the languag detection to a trait instead.

5. Name controller and routes "singular".

For #34 you would have ProjectController->listAction and ProjectController->showAction e.g. :)

D'accord?

**Comment by erikaheidi** [comment]
This is great feedback, thank you! I will implement these changes now.

**Comment by pulponair** [comment]
@erikaheidi 
One thing: you should consinder using the primary key or a unique slug as controller argument instead of the title.

In Laravel route model binding is one way to archive that (see: https://laravel.com/docs/5.2/routing#route-model-binding)

Sample:
https://stackoverflow.com/a/34485411

**Comment by erikaheidi** [comment]
@pulponair the label title was definitely a mistake, I should have created a slug but I ended up just replicating what Github sends me via the API. I will work on a fix in a separate PR. Thank you so much for your review!

**Pull request merged**
